{% set name = "term-image" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/term-image-{{ version }}.tar.gz
  sha256: d62d85b62b58a90576b2dc22478aeee7eb71bfac169862a0abc94c9f494c8b0c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - pillow >=9.1,<10.0
    - python >=3.7
    - requests >=2.23,<3.0

test:
  imports:
    - term_image
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/AnonymouX47/term-img
  summary: Display images in the terminal
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
