{% set name = "term-image" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/term-image-{{ version }}.tar.gz
  sha256: 8895e47d71d21c8102a6069510be7e844a1cf809f543db6209b8648c790216ca

build:
  entry_points:
    - term-img=term_img.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - pillow >=8.3,<10.0
    - python >=3.6
    - requests >=2.23,<3.0
    - urwid >=2.1,<3.0

test:
  imports:
    - term_img
  commands:
    - pip check
    - term-img --help
  requires:
    - pip

about:
  home: https://github.com/AnonymouX47/term-img
  summary: Display images in the terminal
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
