{% set name = "term-image" %}
{% set version = "0.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/term-image-{{ version }}.tar.gz
  sha256: 607456bd0496dc9ae4925477d239c7d012ef857a31b2317f1f5455c417190b0b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - pillow >=9.1,<11
    - python >=3.7
    - requests >=2.23,<3.0

test:
  imports:
    - term_image
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/AnonymouX47/term-img
  summary: Display images in the terminal
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
