{% set name = "term-image" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/term-image-{{ version }}.tar.gz
  sha256: 37f0b0d3e33561bd068dfe7b85869900f0d3ba701c57032b3d111a69d36fe265

build:
  entry_points:
    - term-image=term_image.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - pillow >=9.1,<10.0
    - python >=3.7
    - requests >=2.23,<3.0
    - urwid >=2.1,<3.0

test:
  imports:
    - term_img
  commands:
    - pip check
    - term-image --help
  requires:
    - pip

about:
  home: https://github.com/AnonymouX47/term-img
  summary: Display images in the terminal
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
