{% set name = "term-image" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/term-image-{{ version }}.tar.gz
  sha256: 8c9aaf03692bdc7d278ef20ffb726b3f28edb7296680e0f6df759d54a44cfd45

build:
  entry_points:
    - term-image=term_image.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - pillow >=9.1,<10.0
    - python >=3.7
    - requests >=2.23,<3.0
    - urwid >=2.1,<3.0

test:
  imports:
    - term_image
  commands:
    - pip check
    - term-image --help
  requires:
    - pip

about:
  home: https://github.com/AnonymouX47/term-img
  summary: Display images in the terminal
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
